# Generated by Django 4.0.6 on 2022-09-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('work_instruction', models.CharField(max_length=10)),
                ('report_form', models.CharField(max_length=10)),
                ('test_duration_in_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('letter', models.CharField(max_length=1)),
                ('is_online', models.BooleanField()),
                ('capable_tests', models.ManyToManyField(to='test_lab_schedule.labtestinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=255)),
                ('part1', models.CharField(max_length=255)),
                ('part2', models.CharField(blank=True, max_length=255, null=True)),
                ('part1_agile', models.CharField(max_length=10)),
                ('part2_agile', models.CharField(blank=True, max_length=10, null=True)),
                ('part1_manu', models.CharField(max_length=255)),
                ('part2_manu', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.reporter')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('QUEUE', 'Test Queue'), ('MC', 'Meets Criteria'), ('DNMC', 'Does Not Meet Criteria'), ('RND', 'R&D Test Complete'), ('CANCEL', 'Cancelled')], max_length=6)),
                ('lims', models.IntegerField()),
                ('start_date', models.DateField()),
                ('labtestinfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.labtestinfo')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.machine')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_lab_schedule.sample')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.technician')),
            ],
        ),
    ]
