# Generated by Django 4.0.6 on 2022-09-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='letter',
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
