# Generated by Django 4.0.6 on 2022-09-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0002_remove_machine_letter_alter_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='capable_tests',
            field=models.ManyToManyField(blank=True, to='test_lab_schedule.labtestinfo'),
        ),
    ]
