# Generated by Django 4.0.6 on 2022-09-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0003_alter_machine_capable_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='email',
            field=models.EmailField(default='morban@specialized.com', max_length=254),
        ),
    ]
