# Generated by Django 4.0.6 on 2022-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0005_rename_test_name_labtestinfo_test_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestinfo',
            name='report_form',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='labtestinfo',
            name='standard',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labtestinfo',
            name='work_instruction',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
