# Generated by Django 4.0.6 on 2022-09-07 03:45

from django.db import migrations, models
import django.db.models.deletion
import test_lab_schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0006_alter_labtestinfo_report_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='morban@specialized.com', max_length=254)),
                ('role', models.CharField(choices=[('TECH', 'Technician'), ('REPORT', 'Reporter'), ('STAKE', 'Stakeholder')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.technician', validators=[test_lab_schedule.models.is_technician]),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('samples', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.sample')),
                ('stakeholders', models.ManyToManyField(to='test_lab_schedule.people')),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.people'),
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
