# Generated by Django 4.0.6 on 2022-09-07 03:47

from django.db import migrations, models
import django.db.models.deletion
import test_lab_schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0007_people_alter_test_technician_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_lab_schedule.people', validators=[test_lab_schedule.models.is_technician]),
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
