# Generated by Django 4.0.6 on 2022-09-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0009_alter_sample_bike_model_alter_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='part2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
