# Generated by Django 4.0.6 on 2022-09-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0011_alter_test_lims'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='part1_dimensions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sample',
            name='part2_dimensions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.CharField(choices=[('TC', 'Technician'), ('SH', 'Stakeholder'), ('DV', 'Developer'), ('CP', 'Compliance')], max_length=255),
        ),
    ]
