# Generated by Django 4.0.6 on 2022-09-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0012_sample_part1_dimensions_sample_part2_dimensions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField()),
                ('bike_model', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='bike_model',
        ),
        migrations.AddField(
            model_name='sample',
            name='bike_model',
            field=models.ManyToManyField(to='test_lab_schedule.bike'),
        ),
    ]
