# Generated by Django 4.0.6 on 2022-09-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lab_schedule', '0013_bike_remove_sample_bike_model_sample_bike_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stakeholders', models.ManyToManyField(to='test_lab_schedule.people')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
