# Generated by Django 4.0.6 on 2022-07-29 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MfrPartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agile_number', models.CharField(max_length=10, unique=True)),
                ('lifecycle', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('part_type', models.CharField(max_length=64)),
                ('names_list', models.ManyToManyField(related_name='part', to='reports.mfrpartname')),
            ],
        ),
        migrations.CreateModel(
            name='TestReportPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agile_number', models.CharField(max_length=10, unique=True)),
                ('lifecycle', models.CharField(default='Preliminary', max_length=16)),
                ('report_type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('contents', models.ManyToManyField(related_name='reports', to='reports.part')),
            ],
        ),
        migrations.CreateModel(
            name='TestReportCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agile_number', models.CharField(max_length=10, unique=True)),
                ('lifecycle', models.CharField(default='Preliminary', max_length=16)),
                ('report_type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
                ('part', models.ManyToManyField(related_name='trc', to='reports.part')),
                ('trp', models.ManyToManyField(related_name='trc', to='reports.testreportpart')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
                ('model_year', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=4)),
                ('bb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_bb', to='reports.part')),
                ('cs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_cs', to='reports.part')),
                ('fork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_fork', to='reports.part')),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_frame', to='reports.part')),
                ('handlebar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_handlebar', to='reports.part')),
                ('saddle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_saddle', to='reports.part')),
                ('seatpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_seatpost', to='reports.part')),
                ('stem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_stem', to='reports.part')),
            ],
        ),
    ]
