# Generated by Django 4.0.6 on 2022-08-02 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreportpart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(1974, 1, 1, 0, 0)),
        ),
    ]
