# Generated by Django 4.0.6 on 2022-08-10 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_testreportpart_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreportcombo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(1974, 1, 1, 0, 0)),
        ),
    ]
