# Generated by Django 4.0.6 on 2022-08-22 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_testreportcombo_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=6)),
                ('agile_number', models.CharField(max_length=10)),
                ('first_prod_date', models.DateField(default=datetime.datetime(1974, 1, 1, 0, 0))),
                ('description', models.CharField(max_length=512)),
                ('has_attachment', models.BooleanField()),
                ('ebike', models.BooleanField()),
                ('trc_list', models.ManyToManyField(related_name='br_trc', to='reports.testreportcombo')),
                ('trp_list', models.ManyToManyField(related_name='br_trp', to='reports.testreportpart')),
            ],
        ),
        migrations.CreateModel(
            name='BomBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
                ('model_year', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=4)),
                ('bb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_bb', to='reports.part')),
                ('cs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_cs', to='reports.part')),
                ('fork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_fork', to='reports.part')),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_frame', to='reports.part')),
                ('handlebar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_handlebar', to='reports.part')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bombike', to='reports.bikereport')),
                ('saddle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_saddle', to='reports.part')),
                ('seatpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_seatpost', to='reports.part')),
                ('stem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bikes_stem', to='reports.part')),
            ],
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
