# Generated by Django 4.0.6 on 2022-09-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_bikereport_ebike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombike',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bombike', to='reports.bikereport'),
        ),
    ]
