# Generated by Django 4.0.6 on 2022-09-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_bombike_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikereport',
            old_name='pid',
            new_name='lifecycle',
        ),
    ]
