# Generated by Django 4.0.6 on 2022-10-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_lifecycle_bikereport_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bombike',
            name='model_year',
        ),
    ]
