# Generated by Django 4.0.6 on 2022-10-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_bombike_production_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bombike',
            old_name='pid',
            new_name='report',
        ),
    ]
