# Generated by Django 4.0.6 on 2022-11-08 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_testreportcombo_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbcProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agile_number', models.CharField(max_length=10)),
                ('tla', models.ManyToManyField(related_name='sbc_project', to='reports.part')),
                ('trp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sbc_project', to='reports.testreportpart')),
            ],
        ),
    ]
