# Generated by Django 4.0.6 on 2022-11-08 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_sbcproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbcproject',
            name='trp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sbc_project', to='reports.testreportpart'),
        ),
    ]
