# Generated by Django 4.0.6 on 2022-11-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_sbcproject_trp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbcproject',
            name='trp',
        ),
        migrations.AddField(
            model_name='sbcproject',
            name='trp',
            field=models.ManyToManyField(related_name='sbc_project', to='reports.testreportpart'),
        ),
    ]
